services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ahmazing_backend
    restart: always
    ports:
      - "5001:80"
    environment:
      ADMIN_EMAIL: afutunde@gmail.com
    volumes:
      - ./backend:/var/www/html
