version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: ahmazing_db
    restart: always
    environment:
      POSTGRES_DB: ahmazing_db
      POSTGRES_USER: ahmazing_user
      POSTGRES_PASSWORD: ahmazing_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ahmazing_backend
    restart: always
    ports:
      - "5001:80"
    environment:
      DB_DRIVER: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ahmazing_db
      DB_USER: ahmazing_user
      DB_PASS: ahmazing_pass
      ADMIN_EMAIL: ahmazingfoodsorders@gmail.com
    depends_on:
      - db

volumes:
  pgdata:
